### ISSUE TITLE
Question, not an issue

### ISSUE THREAD

**Issue by kuatroka** [elsaifym/EDGAR-Parsing#1]
Thanks for the code and the files you shared through Dropbox. 
I got a question, when I look at the final csv file, holdings.csv it doesn't have the CUSIP column there, only PERN. Is there a mapping table somewhere so I can link PERN to CUSIP ?
Thanks

**Comment by elsaifym** [comment]
The crspq.csv file has the permno-cusip mapping

**Comment by kuatroka** [comment]
Thanks a lot. In case you need a Python version of the code that parses xml filings, and as a thank you for you're sharing your data, I'll be happy to share my very "naive" code that does the trick. It's "naive" because I'm not a proper developer.
